### ISSUE TITLE
Options Not Being Set Correctly

### ISSUE THREAD

**Issue by rgelhausen** [reduxframework/customizer-integration#3]
For many of the options in the customizer the options are being set to the previous selection.  

In other words, we have set up a color field for the navigation bar and if I were to change the navigation bar color to red, nothing happens. Then if I change it to green, the nav bar changes to red. Then if I change it to blue, it changes to green.

The options are not being set on the initial change and are always one "step" behind.

Here is a link to a video replicating the error.

https://www.dropbox.com/sh/ugjee80tm4puri2/AAAqdBqtGHtIFSTFPYvcZgJoa?dl=0

**Comment by dovy** [comment]
Actually fixed this already. It will be in a push shortly.  ;)

**Comment by dovy** [comment]
Should have been pushed a bit ago. Please verify.  :)
