### ISSUE TITLE
"required" parameter doesn't work in customizer

### ISSUE THREAD

**Issue by Surgeonito** [reduxframework/customizer-integration#4]
Hi,
Thanks for great work with Advanced Customizer extension, but unfortunatelly it has some flaws.
Even on demo page http://demo.redux.io/wp-admin/customize.php Switch & Button Set >> Switch you can easily see that the reqired parameter is not working as it should. 
It works fine in 'Theme option' mode.
Update:: i noticed (on https://ideas.reduxframework.com/campaigns/complete-customizer-integration/) that 'Required' parameter is listed as feature not working curently. When it'll be ready?

**Comment by kprovance** [comment]
See:  https://ideas.reduxframework.com/campaigns/complete-customizer-integration/  It's listened under 'not working'.  No ETA when it might.
