### ISSUE TITLE
3.5.9.8 breaks customizer (missing forward slash for css file)

### ISSUE THREAD

**Issue by kmob2** [reduxframework/customizer-integration#8]
Hello,

I was on redux 3.5.8.10 and just updated to 3.5.9.8 and I noticed that when I load the customizer, it's all blank. Looking at the console, it tells me the /wp-content/themes/mytheme/redux-framework.3.5.9.8/ReduxCore/inc/extensions/customizerextension_customizer.css?ver=1460655606 could not be loaded.
As you can see there is a missing forward slash at the very last folder. customizer/extension_customizer.css

I would quickly fix this myself, but I don't know in what file this css is being loaded.

Edit:
Same file the file customizer/extension_customizer.min.js?ver=2.0.0 
It tries to load customizerextension_customizer.min.js?ver=2.0.0

**Comment by kmob2** [comment]
Update, found the file:
ReduxCore/inc/extensions/customizer/extension_customizer.php

Line 145 for the css
Line 149 for the js file

Would be nice to have this fixed asap for everyone else, considering it completely breaks the customizer.

**Comment by dovy** [comment]
Pushed.  :)
